# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artistshare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_type', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('art_hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cover_logo', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
