# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_artistshare_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artflagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flag_liked', models.BooleanField(default=False)),
                ('is_flag_notify', models.BooleanField(default=False)),
                ('is_flag_notify_read', models.BooleanField(default=False)),
                ('flag_created', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Artistshare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artliked',
            name='is_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artliked',
            name='is_notify_read',
            field=models.BooleanField(default=False),
        ),
    ]
