# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171117_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistshare',
            name='flag_count',
            field=models.IntegerField(default=0),
        ),
    ]
