# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_artistshare_flag_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gethired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('my_skill', models.CharField(choices=[('painter', 'Painter'), ('musician', 'Musician'), ('band', 'Band'), ('photography', 'Photography'), ('blogger', 'Blogger')], default='painter', max_length=25)),
                ('country', models.CharField(max_length=250)),
                ('hourly_charge', models.CharField(max_length=250)),
                ('email_id', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=25)),
                ('personal_details', models.CharField(max_length=500)),
                ('is_hired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_skill', models.CharField(choices=[('painter', 'Painter'), ('musician', 'Musician'), ('band', 'Band'), ('photography', 'Photography'), ('blogger', 'Blogger')], default='painter', max_length=25)),
                ('country', models.CharField(max_length=250)),
                ('total_hour_work', models.IntegerField(default=0)),
                ('budget', models.CharField(max_length=250)),
                ('email_id', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=25)),
                ('skill_description', models.CharField(max_length=500)),
                ('is_hired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
