# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_gethired_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='gethired',
            name='gethire_post_created',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='hire',
            name='hire_post_created',
            field=models.DateTimeField(default=None),
        ),
    ]
