# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20171208_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gethired',
            name='gethire_post_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='hire_post_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
