# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20171208_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='count_apply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hire',
            name='count_view',
            field=models.IntegerField(default=0),
        ),
    ]
