# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20171209_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hirereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email_id', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('remark', models.CharField(max_length=250)),
                ('req_time', models.DateTimeField(auto_now_add=True)),
                ('hire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Hire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
