# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_hirereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='First Name', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='i_like_being',
            field=models.CharField(choices=[('painter', 'Painter'), ('musician', 'Musician'), ('band', 'Band'), ('photography', 'Photography'), ('blogger', 'Blogger')], default='painter', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_pic',
            field=models.FileField(default='/my_image', upload_to=''),
        ),
    ]
