# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20171217_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_album', models.CharField(default='Sample Album', max_length=250)),
                ('music_album', models.CharField(default='Music Album', max_length=250)),
                ('photo_album', models.CharField(default='Photo Album', max_length=250)),
                ('song_title', models.CharField(default='Sample Song', max_length=250)),
                ('music_type', models.CharField(default='Music Type', max_length=250)),
                ('band_name', models.CharField(default='Band Name', max_length=250)),
                ('blog_name', models.CharField(max_length=250)),
                ('sample_blog', models.CharField(max_length=1500)),
                ('sample_file', models.FileField(upload_to='')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('is_painter', models.BooleanField(default=False)),
                ('is_photography', models.BooleanField(default=False)),
                ('is_musician', models.BooleanField(default=False)),
                ('is_band', models.BooleanField(default=False)),
                ('is_blog', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
