# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_gethirereq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_type', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('seller_name', models.CharField(max_length=250)),
                ('total_count_product', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('art_sold_hidden', models.BooleanField(default=False)),
                ('seller_email_id', models.CharField(max_length=250)),
                ('seller_phone_number', models.IntegerField(max_length=25)),
                ('seller_delivery_charge', models.FloatField(default=0.0)),
                ('count_view', models.IntegerField(default=0)),
                ('art_cover_logo', models.FileField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
