# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_sellart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProductAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_files', models.FileField(upload_to='')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('album_name', models.CharField(default='Product Album', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='sellart',
            name='seller_phone_number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='sellproductalbum',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Sellart'),
        ),
        migrations.AddField(
            model_name='sellproductalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
