# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_sellart_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellart',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
